### ISSUE TITLE
please terminate JS statements with semicolon

### ISSUE THREAD

**Issue by sebudde** [skolmer/i18n-tag-examples#2]
Hi Steffen.

Webstorm code analysis is complaining about missing termination of JS statements.
Please add semicolons even if they are not necessary with ES2015 ;)
Thanks!

seb.

**Comment by skolmer** [comment]
This can be disabled in CodeStyle settings of the project: http://stackoverflow.com/a/31584542/1787868

I think this is more a question of style. I personally prefer ES2015 style without semicolon line terminations.

**Comment by sebudde** [comment]
OK. Thanks.
